version: '3.1'

services:

  airflow-db:
    image: postgres:13
    restart: always
    environment: 
        # - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflowdb
    volumes:
      - airflow-docker-db:/var/lib/postgresql/data
    ports:
     - 5434:5432

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080


volumes: 
    airflow-docker-db: